#!/bin/bash


echo "hello $LOGNAME"
echo "welcome to the world of linux automation"
echo "the host name is `hostname`"
echo "your present working directory is `pwd`"
echo "thank you,see you soon $LOGNAME"


